### ISSUE TITLE
Remove generic instances

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/acc#5]
`Acc` and `NeAcc` both derive `Generic` and `Generic1` instances, which is generally inappropriate for types that are supposed to be abstract. Deriving `Generic` smashes the abstraction barrier. One option would be to make the public types `newtypes` around internal types that derive `Generic`, but I'm not sure it's worth the trouble in this case.

**Comment by nikita-volkov** [comment]
I agree. I'll have it scheduled for future releases.

**Comment by nikita-volkov** [comment]
Done in 0.2
