### ISSUE TITLE
snoc parameter order should be reversed

### ISSUE THREAD

**Issue by cjay** [nikita-volkov/acc#8]
Typical `snoc` seems to have the container as the first parameter and the element as the second, it's that way for `DList`, `Vector`, `ByteString` and others.

**Comment by nikita-volkov** [comment]
Yeah I know. The typical `snoc` also violates [the convention](https://wiki.haskell.org/Parameter_order) of having the affected data-structure as the last parameter making the function unfit for piping. IOW the order of parameters in the typical `snoc` is a historic mistake. I don't want to proliferate it.
